version: "3.5"
services:
  postgres:
    container_name: postgres
    image: postgres
    #restart: always
    volumes:
      - postgres_datavolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - db-pgsql
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    #restart: always
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=breq@brain.de
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      - db-pgsql

volumes:
  postgres_datavolume:

networks:
  ingress:
    name: ingress
    driver: bridge
  db-pgsql:
    name: db-pgsql
    driver: bridge
  paperless_gillert:
    name: paperless_gillert
    driver: bridge
